### ISSUE TITLE
Rapidhash

### ISSUE THREAD

**Issue by hoxxep** [eldruin/wyhash-rs#16]
Hey. I wanted to raise that [wyhash](https://github.com/wangyi-fudan/wyhash) has evolved into [rapidhash](https://github.com/Nicoshev/rapidhash) from the original wyhash creator.

I've recently released a [rapidhash rust port](https://github.com/hoxxep/rapidhash) in case it's of interest.

Cheers,
Liam

**Comment by eldruin** [comment]
Great to see the ecosystem evolve. Have fun!
